package ca.uwo.eng.se2205b;

import java.util.Scanner;

/**
 * Created by Gautham on 2017-01-24.
 */

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2Euler {

    public static void main(String[]args){
        int n;
        System.out.print("Enter number: ");
        Scanner scan = new Scanner(System.in);
        n = scan.nextInt();
        int[] fibonacci= new int[n];
        fibonacci[0]=1;
        fibonacci[1]=2;
            for (int i = 2; i < n; i++) {
                fibonacci[i] = fibonacci[i - 1] + fibonacci[i - 2];
                if(fibonacci[i] >= 4000000){
                    System.out.println("Over 4 million");
                    System.exit(0);
                }
            }
        System.out.println(fibonacci[n - 1]);
    }

}
